# Generated by Django 2.2.1 on 2019-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(verbose_name='Description du site (apparait dans les moteurs de cherche)'),
        ),
    ]
