# Generated by Django 2.2.1 on 2019-05-13 13:08

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configuration', '0002_auto_20190513_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='logo',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='favicon',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favicon', to=settings.FILER_IMAGE_MODEL, verbose_name='Icône dans le navigateur'),
        ),
    ]
