# Generated by Django 2.2.1 on 2019-05-13 18:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20190513_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='favicon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to=settings.FILER_IMAGE_MODEL, verbose_name='Icône dans le navigateur'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo'),
        ),
    ]
