# Generated by Django 2.2.1 on 2019-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20190513_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='analytics',
            field=models.TextField(blank=True, null=True, verbose_name='Code Google Analytics'),
        ),
    ]
