# Generated by Django 2.2.1 on 2019-05-19 19:17

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('configuration', '0005_configuration_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='networks_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networks_logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo pour les réseaux sociaux (recommandé : 1200*630px)'),
        ),
    ]
