# Generated by Django 2.2.1 on 2019-05-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_auto_20190512_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='IndustriesSection',
        ),
    ]
