# Generated by Django 2.2.1 on 2019-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0003_auto_20190512_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustriesSection',
            new_name='IndustriesContent',
        ),
        migrations.AlterModelOptions(
            name='industriescontent',
            options={'verbose_name': 'Contenu de section'},
        ),
    ]
