# Generated by Django 2.2.1 on 2019-05-12 16:24

from django.conf import settings
from django.db import migrations
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0006_auto_20190512_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriescontent',
            name='background',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete='test', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond'),
        ),
    ]
