# Generated by Django 2.2.1 on 2019-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0010_auto_20190512_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriescontent',
            name='heading',
            field=models.TextField(null=True, verbose_name='Entête'),
        ),
        migrations.AlterField(
            model_name='industriescontent',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
    ]
