# Generated by Django 2.2.1 on 2019-05-13 12:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0015_auto_20190512_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriescontent',
            name='heading',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Entête'),
        ),
    ]
