# Generated by Django 2.2.1 on 2019-05-13 18:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0016_auto_20190513_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriescontent',
            name='background',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond'),
        ),
    ]
