# Generated by Django 2.2.1 on 2019-05-14 16:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.IntegerField(verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Prestation',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Entête')),
                ('text_before_list', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte avant la liste')),
            ],
            options={
                'verbose_name': 'Contenu',
            },
        ),
    ]
