# Generated by Django 2.2.1 on 2019-05-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingcontent',
            name='text_before_list',
        ),
    ]
