# Generated by Django 2.2.1 on 2019-05-14 16:17

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('pricing', '0002_remove_pricingcontent_text_before_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingcontent',
            name='background',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_background', to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond'),
        ),
    ]
