# Generated by Django 2.2.1 on 2019-05-14 10:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Entête')),
            ],
            options={
                'verbose_name': 'Contenu',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du partenaire')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lien du partenaire')),
                ('order', models.IntegerField(verbose_name="Ordre d'affichage")),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo du partenaire')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'ordering': ['order'],
            },
        ),
    ]
