# Generated by Django 2.2.1 on 2019-05-14 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentcontent_text_before_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
