# Generated by Django 2.2.1 on 2019-05-14 13:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Entête')),
                ('text_before_scenarios', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte avant le bloc scénario')),
                ('scenario_title', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Titre du bloc scénario')),
                ('scenario_inhabited_tooltip', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tooltip pour "Zone peuplée"')),
                ('scenario_in_sight_tooltip', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tooltip pour "Drone en visuel"')),
                ('scenario_no', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte "Aucun scénario"')),
                ('scenario_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte "Scénario 1"')),
                ('scenario_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte "Scénario 2"')),
                ('scenario_3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte "Scénario 3"')),
                ('scenario_4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte "Scénario 4"')),
                ('text_after_scenarios', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte après le bloc scénario')),
            ],
            options={
                'verbose_name': 'Contenu',
            },
        ),
    ]
