# Generated by Django 2.2.1 on 2019-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationscontent',
            name='scenario_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du bloc scénario'),
        ),
    ]
