# Generated by Django 2.2.1 on 2019-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_auto_20190514_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationscontent',
            name='scenario_in_sight_tooltip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tooltip pour "Drone en visuel"'),
        ),
        migrations.AlterField(
            model_name='regulationscontent',
            name='scenario_inhabited_tooltip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tooltip pour "Zone peuplée"'),
        ),
    ]
