# Generated by Django 2.2.1 on 2019-05-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcontent',
            options={'verbose_name': 'Contenu'},
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Lien FB'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='facebook_plugin',
            field=models.URLField(blank=True, null=True, verbose_name='Lien plugin FB'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='vimeo',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Viméo'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Youtube'),
        ),
    ]
