# Generated by Django 2.2.1 on 2020-01-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190729_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontent',
            name='map',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien Google map'),
        ),
    ]
