# Generated by Django 2.2.1 on 2020-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactcontent_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='email_subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Sujet de l'email précédant le sujet rempli dans le formulaire du contact."),
        ),
    ]
