# Generated by Django 2.2.1 on 2020-01-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20200103_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='facebook_plugin',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien plugin FB'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='map',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien Google map'),
        ),
    ]
