# Generated by Django 2.2.1 on 2019-05-13 10:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuscontent',
            name='first_item_description',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Description du premier point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='first_item_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image du premier point'),
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='first_item_title',
            field=models.CharField(default='test', max_length=200, verbose_name='Titre du premier point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='second_item_description',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Description du second point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='second_item_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image du second point'),
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='second_item_title',
            field=models.CharField(default='test', max_length=200, verbose_name='Titre du second point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='third_item_description',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Description du troisième point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='third_item_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image du troisième point'),
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='third_item_title',
            field=models.CharField(default='tes', max_length=200, verbose_name='Titre du troisième point'),
            preserve_default=False,
        ),
    ]
