# Generated by Django 2.2.1 on 2019-05-13 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20190513_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuscontent',
            name='more_content',
            field=ckeditor.fields.RichTextField(default='test', verbose_name="Contenu du bloc d'informations supplémentaires"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='more_title',
            field=models.CharField(default='test', max_length=200, verbose_name="Titre du bloc d'informations supplémentaires"),
            preserve_default=False,
        ),
    ]
