# Generated by Django 2.2.1 on 2019-05-13 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20190513_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='first_item_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description du premier point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='first_item_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du premier point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='second_item_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description du second point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='second_item_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du second point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='third_item_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description du troisième point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='third_item_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du troisième point'),
        ),
    ]
