# Generated by Django 2.2.1 on 2019-05-13 18:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20190513_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='first_item_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image du premier point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='second_item_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image du second point'),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='third_item_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_item_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image du troisième point'),
        ),
    ]
