# Generated by Django 2.2.1 on 2019-05-14 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20190513_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuscontent',
            name='text_after_more',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Texte après le bloc d'informations supplémentaires"),
        ),
        migrations.AddField(
            model_name='aboutuscontent',
            name='text_before_more',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Texte avant le bloc d'informations supplémentaires"),
        ),
    ]
