# Generated by Django 2.2.1 on 2019-05-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aboutus', '0007_auto_20190514_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.IntegerField(verbose_name="Ordre d'affichage")),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_info_icon', to=settings.FILER_IMAGE_MODEL, verbose_name='Icône')),
            ],
            options={
                'verbose_name': "Point d'information",
                'ordering': ['order'],
            },
        ),
    ]
