# Generated by Django 2.2.1 on 2019-05-13 12:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sous-titre')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien de la vidéo')),
                ('background', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': 'Contenu',
            },
        ),
    ]
