# Generated by Django 2.2.1 on 2019-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre'),
        ),
    ]
