# Generated by Django 2.2.1 on 2019-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190513_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de la vidéo'),
        ),
    ]
