# Generated by Django 2.2.1 on 2019-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliomedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomedia',
            old_name='filtres',
            new_name='filters',
        ),
        migrations.RemoveField(
            model_name='portfoliomedia',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
    ]
