# Generated by Django 2.2.1 on 2019-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190513_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliomedia',
            options={'ordering': ['-order'], 'verbose_name': 'Média'},
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='height',
            field=models.IntegerField(verbose_name='Hauteur de la miniature dans le portfolio (ratio)'),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='order',
            field=models.IntegerField(verbose_name="Ordre d'affichage (le plus grand en premier)"),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='width',
            field=models.IntegerField(verbose_name='Largeur de la miniature dans le portfolio (ratio)'),
        ),
    ]
