# Generated by Django 2.2.1 on 2019-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190513_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomedia',
            name='link',
            field=models.URLField(verbose_name="Lien vers l'image ou la vidéo"),
        ),
    ]
