# Generated by Django 2.2.1 on 2019-05-13 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercontent',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texte'),
        ),
    ]
