# Generated by Django 2.2.1 on 2019-05-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_auto_20190513_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercontent',
            name='background',
        ),
    ]
