# Generated by Django 2.2.1 on 2019-05-14 14:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Entête')),
                ('background', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': 'Contenu',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre')),
                ('order', models.IntegerField(verbose_name="Ordre d'affichage")),
                ('logo', filer.fields.image.FilerImageField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'ordering': ['order'],
            },
        ),
    ]
