# Generated by Django 2.2.1 on 2019-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='lien'),
        ),
    ]
