# Generated by Django 2.2.1 on 2019-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20190514_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien'),
        ),
    ]
